import type { Place, ExploredPlace } from '@/types/Place';

const Places: Place[] = [
  {
    id: 1,
    name: 'Bridge',
    geoWidth: 5,
    geoHeight: 5,
    description: 'test',
    code: '000',
    isDiscovered: true,
    photo: ['/test.webp', 'test2.jpg', 'test3.jpg'],
    category: 'Buildings',
  },
  {
    id: 2,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'Bridge',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/test.webp'],
    category: 'Bridges',
  },
  {
    id: 3,
    description: 'test',
    code: '000',
    isDiscovered: true,
    name: 'HOuse 1',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/test2.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: true,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 5,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 6,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 7,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 8,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 9,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 10,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 11,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
];

const ExploredPlaces: ExploredPlace[] = [
  { id: 1, name: 'Eifle Tower', photo: '/test.webp', category: 'Buildings' },
  {
    id: 2,
    name: 'Grunwald Bridge',
    photo: '/test2.jpg',
    category: 'Buildings',
  },
  {
    id: 3,
    name: 'Politeknika Nova',
    photo: '/test3.jpg',
    category: 'Buildings',
  },
  {
    id: 4,
    name: 'Puchala Wiktor Szandal',
    photo: '/images.jpg',
    category: 'Buildings',
  },
  { id: 1, name: 'Eifle Tower', photo: '/test.webp', category: 'Buildings' },
  {
    id: 2,
    name: 'Grunwald Bridge',
    photo: '/test2.jpg',
    category: 'Buildings',
  },
  {
    id: 3,
    name: 'Politeknika Nova',
    photo: '/test3.jpg',
    category: 'Buildings',
  },
  {
    id: 4,
    name: 'Puchala Wiktor Szandal',
    photo: '/images.jpg',
    category: 'Buildings',
  },
  { id: 1, name: 'Eifle Tower', photo: '/test.webp', category: 'Buildings' },
  {
    id: 2,
    name: 'Grunwald Bridge',
    photo: '/test2.jpg',
    category: 'Buildings',
  },
  {
    id: 3,
    name: 'Politeknika Nova',
    photo: '/test3.jpg',
    category: 'Buildings',
  },
  {
    id: 4,
    name: 'Puchala Wiktor Szandal',
    photo: '/images.jpg',
    category: 'Buildings',
  },
  { id: 1, name: 'Eifle Tower', photo: '/test.webp', category: 'Buildings' },
  {
    id: 2,
    name: 'Grunwald Bridge',
    photo: '/test2.jpg',
    category: 'Buildings',
  },
  {
    id: 3,
    name: 'Politeknika Nova',
    photo: '/test3.jpg',
    category: 'Buildings',
  },
  {
    id: 4,
    name: 'Puchala Wiktor Szandal',
    photo: '/images.jpg',
    category: 'Buildings',
  },
  { id: 1, name: 'Eifle Tower', photo: '/test.webp', category: 'Buildings' },
  {
    id: 2,
    name: 'Grunwald Bridge',
    photo: '/test2.jpg',
    category: 'Buildings',
  },
  {
    id: 3,
    name: 'Politeknika Nova',
    photo: '/test3.jpg',
    category: 'Buildings',
  },
  {
    id: 4,
    name: 'Puchala Wiktor Szandal',
    photo: '/images.jpg',
    category: 'Buildings',
  },
];

export const getPlaces = (): Place[] => {
  return Places;
};

export const getExploredPlaces = (): ExploredPlace[] => {
  return ExploredPlaces;
};
