import type { Place } from '@/types/Place';

const Places: Place[] = [
  {
    id: 1,
    name: 'Bridge',
    geoWidth: 5,
    geoHeight: 5,
    description: 'test',
    code: '000',
    isDiscovered: true,
    photo: ['/test.webp', 'test2.jpg', 'test3.jpg'],
    category: 'Buildings',
  },
  {
    id: 2,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'Bridge',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/test.webp'],
    category: 'Bridges',
  },
  {
    id: 3,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 1',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/test2.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
  {
    id: 4,
    description: 'test',
    code: '000',
    isDiscovered: false,
    name: 'HOuse 2',
    geoWidth: 5,
    geoHeight: 5,
    photo: ['/images.jpg'],
    category: 'Houses',
  },
];

const getPlaces = (): Place[] => {
  return Places;
};
export default getPlaces;
